apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast <1>
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  licenseKeySecretName: hazelcast-license-key
  persistence:
    clusterDataRecoveryPolicy: "FullRecoveryOnly"
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 20Gi
    restore:
      hotBackupResourceName: hot-backup <2>
  agent: <3>
    repository: hazelcast/platform-operator-agent
